"""
Emit CS2 hook signatures as:
    1. C++ header with MAKE_SIGNATURE macros (compile-time)
    2. JSON signature database (runtime-loadable)
    3. C++ runtime loader header (optional)

Output layout (HPP):
    // MAKE_SIGNATURE macros ready to paste into your cheat
    MAKE_SIGNATURE(fnCreateMove, "client.dll", "48 8B C4 4C 89 40 ? ...", 0x0);
    ...

Output layout (JSON):
    {
      "signatures": {
        "fnCreateMove": {
          "module": "client.dll",
          "pattern": "48 8B C4 ...",
          "fallbacks": [...],
          "resolve": "direct",
          "required": true
        }
      }
    }
"""

import json
import os
import re
from datetime import datetime, timezone
from typing import List

from src.engines.source2.hook_signature_dumper import CS2HookSignatureResult
from src.engines.source2.hook_signatures import ALL_HOOK_SIGS, CS2HookSig

_IDENT_RE = re.compile(r"[^A-Za-z0-9_]")


def _sanitize(name: str) -> str:
    return _IDENT_RE.sub("_", name)


# ---------------------------------------------------------------------------
# C++ header writer — MAKE_SIGNATURE macros
# ---------------------------------------------------------------------------

def write_signatures_header(
    path: str,
    process_name: str,
) -> None:
    """Write a C++ header with MAKE_SIGNATURE macros for all defined signatures.

    This does NOT use scan results — it emits the raw pattern table so your
    cheat can resolve them at runtime. Update this file in your C++ project
    whenever you add/change signatures in hook_signatures.py.
    """
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")

    lines: List[str] = []
    lines.append("// Auto-generated by GameSDK Dumper - CS2 Hook Signatures")
    lines.append(f"// Process: {process_name}")
    lines.append(f"// Generated: {ts}")
    lines.append("// Do NOT edit manually — regenerate from dumper and copy-paste.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("// -----------------------------------------------------------------------------")
    lines.append("// Usage in your cheat:")
    lines.append("//   MAKE_SIGNATURE(fnCreateMove, \"client.dll\", \"48 8B C4 ...\", 0x0);")
    lines.append("//   auto addr = S::fnCreateMove();  // resolved at init via PatternScanModule")
    lines.append("// -----------------------------------------------------------------------------")
    lines.append("")

    # Group by module for readability
    by_module: dict = {}
    for sig in ALL_HOOK_SIGS:
        by_module.setdefault(sig.module, []).append(sig)

    for module, sigs in sorted(by_module.items()):
        lines.append(f"// --- {module} ---------------------------------------------------------------")
        for sig in sigs:
            primary = sig.patterns[0] if sig.patterns else ""
            fallbacks = sig.patterns[1:] if len(sig.patterns) > 1 else []
            offset_hex = f"0x{sig.extra_offset:X}" if sig.extra_offset else "0x0"

            if sig.description:
                lines.append(f"// {sig.description}")
            if fallbacks:
                fb_str = ", ".join(f'"{f}"' for f in fallbacks)
                lines.append(f"// fallbacks: {fb_str}")

            req_flag = " // REQUIRED" if sig.required else ""
            lines.append(
                f'MAKE_SIGNATURE({_sanitize(sig.name)}, "{sig.module}", '
                f'"{primary}", {offset_hex});{req_flag}'
            )
            lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


# ---------------------------------------------------------------------------
# JSON signature database — runtime-loadable
# ---------------------------------------------------------------------------

def write_signatures_json(
    path: str,
    process_name: str,
) -> None:
    """Write a JSON signature database your cheat can load at runtime.

    Unlike the prediction JSON, this does NOT contain resolved RVAs.
    It contains the raw patterns so the cheat can scan for them itself.
    """
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")

    sigs_db = {}
    for sig in ALL_HOOK_SIGS:
        primary = sig.patterns[0] if sig.patterns else ""
        fallbacks = sig.patterns[1:] if len(sig.patterns) > 1 else []
        sigs_db[sig.name] = {
            "module": sig.module,
            "pattern": primary,
            "fallbacks": fallbacks,
            "resolve": sig.resolve,
            "disp_offset": sig.disp_offset,
            "instruction_size": sig.instruction_size,
            "extra_offset": sig.extra_offset,
            "required": sig.required,
            "description": sig.description,
        }

    payload = {
        "process": process_name,
        "generated_utc": ts,
        "schema_version": 1,
        "kind": "signature_database",
        "note": (
            "This file contains raw signature patterns, NOT resolved addresses. "
            "Load it at runtime and scan each pattern against the target module."
        ),
        "signatures": sigs_db,
    }

    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


# ---------------------------------------------------------------------------
# JSON validation report — shows what matched after a dump run
# ---------------------------------------------------------------------------

def write_signatures_validation_json(
    path: str,
    results: List[CS2HookSignatureResult],
    process_name: str,
) -> None:
    """Write a validation report showing which signatures matched in the
    current game build. Useful for quickly spotting broken patterns."""
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")

    entries = []
    for r in results:
        entries.append({
            "name": r.name,
            "module": r.module,
            "found": r.found,
            "rva": f"0x{r.rva:X}" if r.found else None,
            "pattern_matched": r.pattern_matched,
            "required": r.required,
            "description": r.description,
            "error": r.error if not r.found else None,
        })

    payload = {
        "process": process_name,
        "generated_utc": ts,
        "summary": {
            "total": len(results),
            "found": sum(1 for r in results if r.found),
            "missing": sum(1 for r in results if not r.found),
            "required_missing": sum(1 for r in results if r.required and not r.found),
        },
        "entries": entries,
    }

    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


# ---------------------------------------------------------------------------
# C++ runtime loader header (optional — for JSON-based runtime loading)
# ---------------------------------------------------------------------------

def write_signatures_loader_header(
    path: str,
    process_name: str,
) -> None:
    """Write a header-only C++ runtime signature loader.

    Include this in your cheat if you want to load cs2_signatures.json at
    runtime instead of using MAKE_SIGNATURE macros.
    """
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")

    lines: List[str] = []
    lines.append("// Auto-generated by GameSDK Dumper - CS2 Runtime Signature Loader")
    lines.append(f"// Process: {process_name}")
    lines.append(f"// Generated: {ts}")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <string>")
    lines.append("#include <vector>")
    lines.append("#include <unordered_map>")
    lines.append("")
    lines.append("struct SignatureDef {")
    lines.append("    std::string name;")
    lines.append("    std::string module;")
    lines.append("    std::string pattern;")
    lines.append("    std::vector<std::string> fallbacks;")
    lines.append("    std::string resolve;  // direct | call | rip | rip_call")
    lines.append("    int disp_offset = 3;")
    lines.append("    int instruction_size = 7;")
    lines.append("    int extra_offset = 0;")
    lines.append("    bool required = false;")
    lines.append("};")
    lines.append("")
    lines.append("// Load cs2_signatures.json and populate this map at runtime.")
    lines.append("// Example (with nlohmann::json):")
    lines.append("//   std::vector<SignatureDef> defs = LoadSignatureDatabase(\"cs2_signatures.json\");")
    lines.append("//   for (auto& d : defs) { uintptr_t addr = PatternScanModule(d.module.c_str(), d.pattern.c_str()); ... }")
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
