"""
Emit CS2 engine-global offsets as a C++ header + JSON.

Output layout (mirrors cs2-dumper convention):

    namespace Offsets {
    namespace client_dll {
        inline constexpr std::ptrdiff_t dwLocalPlayerController = 0x1A3BEC8;
        ...
    }}
"""

import json
import os
import re
from datetime import datetime, timezone
from typing import Iterable, List

from src.engines.source2.globals import CS2GlobalResult


_IDENT_RE = re.compile(r"[^A-Za-z0-9_]")


def _sanitize_ns(name: str) -> str:
    base = name.lower().replace(".dll", "_dll").replace(".exe", "_exe")
    return _IDENT_RE.sub("_", base)


def _group_by_module(results: Iterable[CS2GlobalResult]):
    buckets: dict = {}
    for r in results:
        buckets.setdefault(r.module, []).append(r)
    return sorted(buckets.items(), key=lambda kv: kv[0])


def write_cs2_globals_header(path: str, results: List[CS2GlobalResult], process_name: str) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    ok_count = sum(1 for r in results if r.found)

    lines: List[str] = []
    lines.append("// Auto-generated by UE/Unity Dumper - CS2 Engine Globals")
    lines.append(f"// Process: {process_name}")
    lines.append(f"// Generated: {ts}")
    lines.append(f"// Resolved: {ok_count}/{len(results)}")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace Offsets {")

    for module, items in _group_by_module(results):
        ns = _sanitize_ns(module)
        lines.append(f"namespace {ns} {{")
        lines.append(f"    // Source module: {module}")
        for r in items:
            if r.description:
                lines.append(f"    // {r.description}")
            if r.found:
                lines.append(
                    f"    inline constexpr std::ptrdiff_t {r.name} = 0x{r.rva:X};"
                )
            else:
                lines.append(
                    f"    // [NOT FOUND] {r.name} -- {r.error}"
                )
        lines.append(f"}} // namespace {ns}")
        lines.append("")

    lines.append("} // namespace Offsets")
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def write_cs2_globals_json(path: str, results: List[CS2GlobalResult], process_name: str) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")

    payload: dict = {
        "process": process_name,
        "generated_utc": ts,
        "resolved": sum(1 for r in results if r.found),
        "total": len(results),
        "globals": {},
    }
    for module, items in _group_by_module(results):
        mod_map: dict = {}
        for r in items:
            if r.found:
                mod_map[r.name] = {
                    "rva": f"0x{r.rva:X}",
                    "rva_int": r.rva,
                    "description": r.description,
                }
            else:
                mod_map[r.name] = {"error": r.error, "description": r.description}
        payload["globals"][module] = mod_map

    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
