import os
import re
from datetime import datetime, timezone
from typing import Iterable, List, Tuple

from src.core.models import SDKDump, StructInfo

_IDENT_RE = re.compile(r"[^A-Za-z0-9_]")
_LEADING_DIGIT_RE = re.compile(r"^[0-9]")
_CXX_RESERVED = {
    "alignas", "alignof", "and", "and_eq", "asm", "auto", "bitand", "bitor",
    "bool", "break", "case", "catch", "char", "char8_t", "char16_t", "char32_t",
    "class", "compl", "concept", "const", "const_cast", "consteval", "constexpr",
    "constinit", "continue", "co_await", "co_return", "co_yield", "decltype",
    "default", "delete", "do", "double", "dynamic_cast", "else", "enum",
    "explicit", "export", "extern", "false", "float", "for", "friend", "goto",
    "if", "inline", "int", "long", "mutable", "namespace", "new", "noexcept",
    "not", "not_eq", "nullptr", "operator", "or", "or_eq", "private", "protected",
    "public", "register", "reinterpret_cast", "requires", "return", "short",
    "signed", "sizeof", "static", "static_assert", "static_cast", "struct",
    "switch", "template", "this", "thread_local", "throw", "true", "try",
    "typedef", "typeid", "typename", "union", "unsigned", "using", "virtual",
    "void", "volatile", "wchar_t", "while", "xor", "xor_eq",
}


def _sanitize_ident(s: str) -> str:
    if not s:
        return "_unnamed"
    out = _IDENT_RE.sub("_", s)
    if _LEADING_DIGIT_RE.match(out):
        out = "_" + out
    if out in _CXX_RESERVED:
        out = out + "_"
    return out


def _sanitize_namespace(s: str) -> str:
    if not s:
        return "_anon"
    base = s.lower()
    base = base.replace(".dll", "").replace(".exe", "")
    return _sanitize_ident(base)


def _group_by_scope(structs: Iterable[StructInfo]) -> List[Tuple[str, List[StructInfo]]]:
    buckets: dict[str, List[StructInfo]] = {}
    for s in structs:
        key = s.package or "_anon"
        buckets.setdefault(key, []).append(s)
    return sorted(
        ((k, sorted(v, key=lambda x: x.name)) for k, v in buckets.items()),
        key=lambda kv: kv[0],
    )


def _header_preamble(process_name: str, extra: str = "") -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    lines = [
        "// Auto-generated by UE/Unity Dumper - Source 2 Schema Dump",
        f"// Process: {process_name}",
        f"// Generated: {ts}",
    ]
    if extra:
        lines.append(f"// {extra}")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("#include <cstdint>")
    lines.append("")
    return "\n".join(lines) + "\n"


def _emit_class_block(cls: StructInfo, indent: str) -> List[str]:
    out: List[str] = []
    safe_cls = _sanitize_ident(cls.name)
    out.append(f"{indent}namespace {safe_cls} {{")
    if cls.size:
        out.append(f"{indent}    inline constexpr std::size_t __size = 0x{cls.size:X};")
    if cls.super_name:
        safe_super = _sanitize_ident(cls.super_name)
        out.append(f'{indent}    inline constexpr const char* __parent = "{cls.super_name}";')
        out.append(f'{indent}    // inherits: {safe_super}')
    seen: set[str] = set()
    for m in cls.members:
        raw = m.name or ""
        safe = _sanitize_ident(raw)
        if safe in seen:
            safe = f"{safe}_0x{m.offset:X}"
        seen.add(safe)
        type_comment = f" // {m.type_name}" if m.type_name and m.type_name != "Unknown" else ""
        out.append(
            f"{indent}    inline constexpr std::ptrdiff_t {safe} = 0x{m.offset:X};{type_comment}"
        )
    out.append(f"{indent}}} // namespace {safe_cls}")
    return out


def write_source2_header(path: str, sdk_dump: SDKDump, process_name: str) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)

    grouped = _group_by_scope(sdk_dump.structs)
    total_classes = sum(len(v) for _, v in grouped)
    total_fields = sum(len(s.members) for _, v in grouped for s in v)

    lines: List[str] = []
    lines.append(_header_preamble(
        process_name,
        extra=f"Scopes: {len(grouped)} | Classes: {total_classes} | Fields: {total_fields}",
    ))
    lines.append("namespace Schemas {")
    lines.append("")
    for scope, classes in grouped:
        ns = _sanitize_namespace(scope)
        lines.append(f"// Scope: {scope} ({len(classes)} classes)")
        lines.append(f"namespace {ns} {{")
        for cls in classes:
            lines.extend(_emit_class_block(cls, indent="    "))
            lines.append("")
        lines.append(f"}} // namespace {ns}")
        lines.append("")
    lines.append("} // namespace Schemas")
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def write_source2_sdk(output_dir: str, sdk_dump: SDKDump, process_name: str) -> None:
    os.makedirs(output_dir, exist_ok=True)
    defs_root = os.path.join(output_dir, "Definitions")
    os.makedirs(defs_root, exist_ok=True)

    grouped = _group_by_scope(sdk_dump.structs)

    sdk_includes: List[str] = []
    for scope, classes in grouped:
        ns_dir = _sanitize_namespace(scope)
        scope_path = os.path.join(defs_root, ns_dir)
        os.makedirs(scope_path, exist_ok=True)

        seen_files: set[str] = set()
        for cls in classes:
            base = _sanitize_ident(cls.name)
            fname = base
            suffix = 1
            while fname in seen_files:
                fname = f"{base}__{suffix}"
                suffix += 1
            seen_files.add(fname)

            file_path = os.path.join(scope_path, f"{fname}.h")
            body: List[str] = []
            body.append(_header_preamble(
                process_name,
                extra=f"Scope: {scope} | Class: {cls.name}",
            ))
            body.append(f"namespace Schemas {{ namespace {ns_dir} {{")
            body.extend(_emit_class_block(cls, indent=""))
            body.append("} } // namespace Schemas::" + ns_dir)
            body.append("")
            with open(file_path, "w", encoding="utf-8") as f:
                f.write("\n".join(body))

            sdk_includes.append(f'#include "Definitions/{ns_dir}/{fname}.h"')

    sdk_path = os.path.join(output_dir, "SDK.h")
    with open(sdk_path, "w", encoding="utf-8") as f:
        f.write(_header_preamble(
            process_name,
            extra="Aggregate header — includes every per-class definition.",
        ))
        f.write("\n".join(sdk_includes))
        f.write("\n")
