import json
import os
import re
from datetime import datetime, timezone
from typing import Iterable, List, Optional

from src.core.models import SDKDump
from src.engines.source2.buttons import CS2ButtonResult
from src.engines.source2.globals import CS2GlobalResult
from src.engines.source2.interfaces import CS2InterfaceModuleResult
from src.engines.source2.prediction_dumper import CS2PredictionDump


_IDENT_RE = re.compile(r"[^A-Za-z0-9_]")
_LEADING_DIGIT_RE = re.compile(r"^[0-9]")
_EXPECTED_BUTTONS = {
    "attack",
    "attack2",
    "back",
    "duck",
    "forward",
    "jump",
    "left",
    "reload",
    "right",
    "showscores",
    "use",
    "zoom",
}
_OPTIONAL_PREDICTION_NAMES = {
    "fnRunPrediction",
}


def _now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")


def _sanitize(name: str) -> str:
    out = _IDENT_RE.sub("_", name or "_unnamed")
    if _LEADING_DIGIT_RE.match(out):
        out = "_" + out
    return out


def _sanitize_ns(name: str) -> str:
    base = (name or "_anon").lower().replace(".dll", "_dll").replace(".exe", "_exe")
    return _sanitize(base)


def _button_items(results: Iterable[CS2ButtonResult]) -> List[CS2ButtonResult]:
    return sorted((r for r in results if r.found and r.name), key=lambda item: item.name)


def write_cs2_buttons_header(
    path: str,
    results: List[CS2ButtonResult],
    process_name: str,
) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    items = _button_items(results)
    found_names = {r.name for r in items}
    missing = sorted(_EXPECTED_BUTTONS - found_names)

    lines: List[str] = []
    lines.append("// Auto-generated by UE/Unity Dumper - CS2 Key Buttons")
    lines.append(f"// Process: {process_name}")
    lines.append(f"// Generated: {_now_utc()}")
    lines.append(f"// Resolved: {len(items)}")
    if missing:
        lines.append(f"// Missing expected: {', '.join(missing)}")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace Buttons {")

    modules = sorted({r.module for r in items})
    for module in modules:
        module_items = [r for r in items if r.module == module]
        ns = _sanitize_ns(module)
        lines.append(f"namespace {ns} {{")
        lines.append(f"    // Source module: {module}")
        seen: set[str] = set()
        for r in module_items:
            ident = _sanitize(r.name)
            if ident in seen:
                ident = f"{ident}_0x{r.rva:X}"
            seen.add(ident)
            lines.append(f"    inline constexpr std::ptrdiff_t {ident} = 0x{r.rva:X};")
        lines.append(f"}} // namespace {ns}")
        lines.append("")

    lines.append("} // namespace Buttons")
    lines.append("")

    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))


def write_cs2_buttons_json(
    path: str,
    results: List[CS2ButtonResult],
    process_name: str,
) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    items = _button_items(results)
    found_names = {r.name for r in items}

    payload = {
        "process": process_name,
        "generated_utc": _now_utc(),
        "resolved": len(items),
        "expected": sorted(_EXPECTED_BUTTONS),
        "missing_expected": sorted(_EXPECTED_BUTTONS - found_names),
        "buttons": {},
    }
    for r in items:
        payload["buttons"].setdefault(r.module, {})[r.name] = {
            "rva": f"0x{r.rva:X}",
            "rva_int": r.rva,
            "absolute": f"0x{r.absolute:X}",
        }
    if not items:
        payload["errors"] = [r.error for r in results if r.error]

    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)


def write_cs2_interfaces_header(
    path: str,
    results: List[CS2InterfaceModuleResult],
    process_name: str,
) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    resolved_count = sum(len(r.interfaces) for r in results)

    lines: List[str] = []
    lines.append("// Auto-generated by UE/Unity Dumper - CS2 CreateInterface Registry")
    lines.append(f"// Process: {process_name}")
    lines.append(f"// Generated: {_now_utc()}")
    lines.append(f"// Resolved interfaces: {resolved_count}")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace Interfaces {")
    lines.append("")

    for module in sorted(results, key=lambda item: item.module.lower()):
        if not module.interfaces:
            continue
        ns = _sanitize_ns(module.module)
        lines.append(f"namespace {ns} {{")
        lines.append(f"    // Source module: {module.module}")
        seen: set[str] = set()
        for item in sorted(module.interfaces, key=lambda iface: iface.name):
            ident = _sanitize(item.name)
            if ident in seen:
                ident = f"{ident}_0x{item.rva:X}"
            seen.add(ident)
            lines.append(f"    inline constexpr std::ptrdiff_t {ident} = 0x{item.rva:X};")
        lines.append(f"}} // namespace {ns}")
        lines.append("")

    lines.append("} // namespace Interfaces")
    lines.append("")

    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))


def write_cs2_interfaces_json(
    path: str,
    results: List[CS2InterfaceModuleResult],
    process_name: str,
) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)

    payload = {
        "process": process_name,
        "generated_utc": _now_utc(),
        "resolved_modules": sum(1 for r in results if r.interfaces),
        "resolved_interfaces": sum(len(r.interfaces) for r in results),
        "modules": {},
    }
    for module in sorted(results, key=lambda item: item.module.lower()):
        payload["modules"][module.module] = {
            "base": f"0x{module.base:X}",
            "size": module.size,
            "path": module.path,
            "found": module.found,
            "error": module.error,
            "interfaces": {
                item.name: {
                    "rva": f"0x{item.rva:X}",
                    "rva_int": item.rva,
                    "absolute": f"0x{item.absolute:X}",
                    "create_fn": f"0x{item.create_fn:X}",
                }
                for item in sorted(module.interfaces, key=lambda iface: iface.name)
                if item.found
            },
        }

    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)


def write_cs2_info_json(
    path: str,
    *,
    process_name: str,
    sdk_dump: SDKDump,
    globals_results: List[CS2GlobalResult],
    buttons_results: List[CS2ButtonResult],
    interfaces_results: List[CS2InterfaceModuleResult],
    prediction_dump: Optional[CS2PredictionDump] = None,
    build_number: int = 0,
    modules: Optional[List[dict]] = None,
    elapsed_seconds: float = 0.0,
) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)

    buttons = _button_items(buttons_results)
    button_names = {r.name for r in buttons}
    missing_buttons = sorted(_EXPECTED_BUTTONS - button_names)
    interface_count = sum(len(r.interfaces) for r in interfaces_results)
    globals_ok = sum(1 for r in globals_results if r.found)
    pred_results = prediction_dump.all_results if prediction_dump else []
    pred_required = [
        r
        for r in pred_results
        if r.name not in _OPTIONAL_PREDICTION_NAMES
        and "optional" not in (r.description or "").lower()
    ]
    pred_optional_missing = [
        r.name
        for r in pred_results
        if not r.found
        and (
            r.name in _OPTIONAL_PREDICTION_NAMES
            or "optional" in (r.description or "").lower()
        )
    ]
    pred_ok = sum(1 for r in pred_results if r.found)
    pred_required_ok = sum(1 for r in pred_required if r.found)

    failures: List[str] = []
    if not sdk_dump.enums:
        failures.append("schema enums were not resolved")
    if missing_buttons:
        failures.append("expected key buttons missing: " + ", ".join(missing_buttons))
    if interface_count == 0:
        failures.append("CreateInterface registry yielded no interfaces")
    if globals_results and globals_ok < len(globals_results):
        failures.append(f"engine globals incomplete: {globals_ok}/{len(globals_results)}")
    if pred_required and pred_required_ok < len(pred_required):
        failures.append(f"required prediction offsets incomplete: {pred_required_ok}/{len(pred_required)}")

    payload = {
        "process": process_name,
        "generated_utc": _now_utc(),
        "build_number": build_number,
        "elapsed_seconds": round(float(elapsed_seconds or 0.0), 3),
        "stats": {
            "schema_classes": len(sdk_dump.structs),
            "schema_enums": len(sdk_dump.enums),
            "schema_fields": sum(len(s.members) for s in sdk_dump.structs),
            "globals_resolved": globals_ok,
            "globals_total": len(globals_results),
            "buttons_resolved": len(buttons),
            "interfaces_resolved": interface_count,
            "prediction_resolved": pred_ok,
            "prediction_total": len(pred_results),
            "prediction_required_resolved": pred_required_ok,
            "prediction_required_total": len(pred_required),
        },
        "health": {
            "ok": not failures,
            "failures": failures,
            "missing_expected_buttons": missing_buttons,
            "optional_prediction_missing": pred_optional_missing,
        },
        "modules": modules or [],
    }

    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
